//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaSuBuMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders1
    {
        public Orders1()
        {
            this.Items1 = new HashSet<Items1>();
        }
    
        public int Id { get; set; }
        public int TransactionsId { get; set; }
    
        public virtual ICollection<Items1> Items1 { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
