//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace LuSuBu
{
    public partial class Orders
    {
        public Orders()
        {
            this.Items = new HashSet<Items>();
        }
    
        public int Id { get; set; }
        public int TransactionsId { get; set; }
    
        public virtual ICollection<Items> Items { get; set; }
        public virtual Transactions Transaction { get; set; }
    }
    
}
