//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace LuSuBu
{
    public partial class TransStatus
    {
        public int id { get; set; }
        public string Description { get; set; }
        public int Transaction_Id { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
    
}
