//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace LuSuBu
{
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransItems = new HashSet<TransItem>();
        }
    
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Amount { get; set; }
        public string Token { get; set; }
        public string PayerID { get; set; }
        public System.DateTime Date { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
        public string ReferenceId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<TransItem> TransItems { get; set; }
    }
    
}
